services:
  - type: web
    name: newsbot-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run chat_newsbot_app.py
    autoDeploy: true

cronJobs:
  - name: update-newsbot-index
    schedule: "30 2 * * *"  # runs daily at 08:00 AM IST (02:30 UTC)
    command: python chat_newsbot_setup.py